# Generated by Django 5.1.5 on 2026-01-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Planta', max_length=100, verbose_name='Nombre de la Mascota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('puntos_vida', models.IntegerField(default=100, help_text='0-100, refleja la salud de la planta', verbose_name='Puntos de Vida')),
                ('estado_salud', models.CharField(choices=[('optimo', 'Óptimo'), ('regular', 'Regular'), ('mal', 'Mal'), ('marchito', 'Marchito')], default='optimo', max_length=20, verbose_name='Estado de Salud')),
                ('nivel_evolucion', models.IntegerField(default=1, help_text='Etapa visual de crecimiento de la planta', verbose_name='Nivel de Evolución')),
                ('ultimo_chequeo', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó la salud', verbose_name='Último Chequeo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-puntos_vida'],
            },
        ),
    ]
