# Generated by Django 6.0.1 on 2026-01-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(help_text='Nombre personalizado que le das a tu planta', max_length=100, verbose_name='Sobrenombre de la Mascota'),
        ),
    ]
