# Generated by Django 6.0.2 on 2026-02-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_mascota_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nivel actual de la mascota', verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='total_xp',
            field=models.IntegerField(default=0, help_text='Puntos de experiencia acumulados de la mascota', verbose_name='Experiencia Total'),
        ),
    ]
