# Generated by Django - manual data migration
# Transfer XP and nivel from Profile to Mascota for existing users

from django.db import migrations

def transfer_xp_to_mascota(apps, schema_editor):
    """
    Transfer total_xp and nivel from user Profile to their Mascota.
    """
    Mascota = apps.get_model('pets', 'Mascota')
    Profile = apps.get_model('users', 'Profile')
    
    mascotas = Mascota.objects.all()
    transferred_count = 0
    
    for mascota in mascotas:
        try:
            profile = Profile.objects.get(user=mascota.user)
            
            # Transfer XP and nivel from profile to mascota
            mascota.total_xp = profile.total_xp
            mascota.nivel = profile.nivel
            
            # Update nivel_evolucion based on new nivel
            # This mirrors the logic in _update_nivel_evolucion()
            if mascota.nivel < 5:
                mascota.nivel_evolucion = 1
            elif mascota.nivel <= 15:
                mascota.nivel_evolucion = 2
            elif mascota.nivel <= 30:
                mascota.nivel_evolucion = 3
            elif mascota.nivel <= 50:
                mascota.nivel_evolucion = 4
            else:
                mascota.nivel_evolucion = 5
            
            mascota.save()
            transferred_count += 1
            
        except Profile.DoesNotExist:
            # Skip if profile doesn't exist (shouldn't happen)
            continue
    
    print(f"Transferred XP/nivel for {transferred_count} mascotas")

def reverse_transfer(apps, schema_editor):
    """
    Reverse migration - transfer XP back to Profile.
    """
    Mascota = apps.get_model('pets', 'Mascota')
    Profile = apps.get_model('users', 'Profile')
    
    for mascota in Mascota.objects.all():
        try:
            profile = Profile.objects.get(user=mascota.user)
            profile.total_xp = mascota.total_xp
            profile.nivel = mascota.nivel
            profile.save()
        except Profile.DoesNotExist:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_mascota_nivel_mascota_total_xp'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_xp_to_mascota, reverse_transfer),
    ]
