# Generated by Django 6.0.2 on 2026-02-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_transfer_xp_data'),
    ]

    operations = [
    ]
