# Generated by Django 6.0.2 on 2026-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_especie_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('gizzmo', 'Gizzmo'), ('bulbasaur', 'Bulbasaur'), ('charmander', 'Charmander'), ('gastly', 'Gastly')], default='gizzmo', max_length=20, verbose_name='Especie'),
        ),
    ]
