# Generated by Django 6.0.2 on 2026-04-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_mascota_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='last_health_notified_at',
            field=models.DateTimeField(blank=True, help_text='Evita spam de notificaciones cuando la mascota está mal', null=True, verbose_name='Última Notificación de Salud'),
        ),
    ]
