# Generated by Django 5.1.5 on 2026-01-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Hábito')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del hábito', verbose_name='Descripción')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('personalizada', 'Personalizada')], default='diaria', max_length=20, verbose_name='Frecuencia')),
                ('meta_semanal', models.IntegerField(default=7, help_text='Veces por semana que se debe completar', verbose_name='Meta Semanal')),
                ('activo', models.BooleanField(default=True, help_text='Si el hábito está activo o archivado', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cumplimiento', models.DateField(verbose_name='Fecha de Cumplimiento')),
                ('estado', models.CharField(choices=[('cumplido', 'Cumplido'), ('no_cumplido', 'No Cumplido')], default='cumplido', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, help_text='Notas opcionales sobre el cumplimiento', verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit', verbose_name='Hábito')),
            ],
            options={
                'verbose_name': 'Registro de Hábito',
                'verbose_name_plural': 'Registros de Hábitos',
                'ordering': ['-fecha_cumplimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'activo'], name='habits_habi_user_id_5c6de7_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['fecha_creacion'], name='habits_habi_fecha_c_c76343_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'fecha_cumplimiento'], name='habits_habi_habit_i_0a91a8_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['estado'], name='habits_habi_estado_711867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'fecha_cumplimiento')},
        ),
    ]
