# Generated by Django 6.0.2 on 2026-02-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='categoria',
            field=models.CharField(choices=[('salud', 'Salud'), ('mental', 'Mental'), ('productividad', 'Productividad'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
    ]
