# Generated by Django 6.0.2 on 2026-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='meta_semanal',
        ),
        migrations.AddField(
            model_name='habit',
            name='dias_semana',
            field=models.CharField(default='0,1,2,3,4,5,6', help_text='Índices de días separados por coma (0=Lunes, 6=Domingo)', max_length=20, verbose_name='Días de la Semana'),
        ),
        migrations.AddField(
            model_name='habit',
            name='total_pasos',
            field=models.IntegerField(default=1, help_text='Número de pasos para completar el hábito (Checkpoints)', verbose_name='Total de Pasos'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='pasos_completados',
            field=models.IntegerField(default=0, verbose_name='Pasos Completados'),
        ),
    ]
