# Generated by Django 6.0.2 on 2026-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_categoria_remove_habit_frecuencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='categoria',
            field=models.CharField(choices=[('salud', 'Salud'), ('ejercicio', 'Ejercicio'), ('estudio', 'Estudio'), ('trabajo', 'Trabajo'), ('tarea', 'Tarea'), ('arte', 'Arte')], default='salud', max_length=20, verbose_name='Categoría'),
        ),
    ]
