# Generated by Django 6.0.1 on 2026-04-01 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='habit',
            name='habits_habi_user_id_5c6de7_idx',
        ),
        migrations.AddField(
            model_name='habit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indica si el hábito está en la papelera', verbose_name='Borrado'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'activo', 'is_deleted'], name='habits_habi_user_id_4168b2_idx'),
        ),
    ]
