# Generated by Django 6.0.2 on 2026-04-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habit_habits_habi_user_id_5c6de7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='hora_notificacion',
            field=models.TimeField(blank=True, help_text='Hora a la que se enviará el recordatorio diario', null=True, verbose_name='Hora de Notificación'),
        ),
        migrations.AddField(
            model_name='habit',
            name='notificaciones_activas',
            field=models.BooleanField(default=False, help_text='Si el usuario desea recibir recordatorios para este hábito', verbose_name='Notificaciones Activas'),
        ),
    ]
