# Generated by Django 5.1.5 on 2026-01-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, help_text='Puntos de experiencia acumulados', verbose_name='Experiencia Total')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel actual del usuario', verbose_name='Nivel')),
                ('accesorios_equipados', models.JSONField(blank=True, default=dict, help_text='Accesorios equipados en la mascota (JSON)', verbose_name='Accesorios Equipados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-total_xp'],
            },
        ),
    ]
