# Generated by Django 6.0.2 on 2026-02-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0, help_text='Monedas virtuales para comprar accesorios', verbose_name='Monedas'),
        ),
    ]
