# Generated by Django 6.0.2 on 2026-02-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_daily_reward_date',
            field=models.DateField(blank=True, help_text='Fecha de la última vez que se otorgó la recompensa diaria de monedas', null=True, verbose_name='Última Recompensa Diaria'),
        ),
    ]
