# Generated by Django 6.0.1 on 2026-04-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_google_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='Indica si el usuario completó el flujo de primer inicio de sesión', verbose_name='Completó Onboarding'),
        ),
    ]
